spring:
  application:
    name: backendFortnite
  app:
    url: ${APP_URL:http://localhost:8080/}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/fortnite}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  messages:
    encoding: UTF-8
jwt:
  secret: ${JWT_SECRET}
